name: Stale Issues and PRs
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: "Mark stale issues and PRs"
        uses: actions/stale@v10.1.1
        with:
          # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
          stale-issue-message: ""
          # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
          stale-pr-message: ""
          # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
          close-issue-message: ""
          # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
          close-pr-message: ""
          # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
          days-before-stale: 60 # optional, default is 60
          # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues as stale automatically. Override "days-before-stale" option regarding only the issues.
          days-before-issue-stale: ""
          # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. Override "days-before-stale" option regarding only the pull requests.
          days-before-pr-stale: ""
          # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
          days-before-close: 7 # optional, default is 7
          # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
          days-before-issue-close: ""
          # The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests. Override "days-before-close" option regarding only the pull requests.
          days-before-pr-close: ""
          # The label to apply when an issue is stale.
          stale-issue-label: Stale # optional, default is Stale
          # The label to apply when an issue is closed.
          close-issue-label: ""
          # The labels that mean an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2").
          exempt-issue-labels: ""
          # The reason to use when closing an issue.
          close-issue-reason: not_planned # optional, default is not_planned
          # The label to apply when a pull request is stale.
          stale-pr-label: Stale # optional, default is Stale
          # The label to apply when a pull request is closed.
          close-pr-label: ""
          # The labels that mean a pull request is exempt from being marked as stale. Separate multiple labels with commas (eg. "label1,label2").
          exempt-pr-labels: ""
          # The milestones that mean an issue or a pull request is exempt from being marked as stale. Separate multiple milestones with commas (eg. "milestone1,milestone2").
          exempt-milestones: ""
          # The milestones that mean an issue is exempt from being marked as stale. Separate multiple milestones with commas (eg. "milestone1,milestone2"). Override "exempt-milestones" option regarding only the issues.
          exempt-issue-milestones: ""
          # The milestones that mean a pull request is exempt from being marked as stale. Separate multiple milestones with commas (eg. "milestone1,milestone2"). Override "exempt-milestones" option regarding only the pull requests.
          exempt-pr-milestones: ""
          # Exempt all issues and pull requests with milestones from being marked as stale. Default to false.
          exempt-all-milestones: false # optional, default is false
          # Exempt all issues with milestones from being marked as stale. Override "exempt-all-milestones" option regarding only the issues.
          exempt-all-issue-milestones: ""
          # Exempt all pull requests with milestones from being marked as stale. Override "exempt-all-milestones" option regarding only the pull requests.
          exempt-all-pr-milestones: ""
          # Only issues or pull requests with all of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels.
          only-labels: ""
          # Only issues or pull requests with at least one of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels.
          any-of-labels: ""
          # Only issues with at least one of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels. Override "any-of-labels" option regarding only the issues.
          any-of-issue-labels: ""
          # Only pull requests with at least one of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels. Override "any-of-labels" option regarding only the pull requests.
          any-of-pr-labels: ""
          # Only issues with all of these labels are checked if stale. Defaults to `[]` (disabled) and can be a comma-separated list of labels. Override "only-labels" option regarding only the issues.
          only-issue-labels: ""
          # Only pull requests with all of these labels are checked if stale. Defaults to `[]` (disabled) and can be a comma-separated list of labels. Override "only-labels" option regarding only the pull requests.
          only-pr-labels: ""
          # The maximum number of operations per run, used to control rate limiting (GitHub API CRUD related).
          operations-per-run: 30 # optional, default is 30
          # Remove stale labels from issues and pull requests when they are updated or commented on.
          remove-stale-when-updated: true # optional, default is true
          # Remove stale labels from issues when they are updated or commented on. Override "remove-stale-when-updated" option regarding only the issues.
          remove-issue-stale-when-updated: ""
          # Remove stale labels from pull requests when they are updated or commented on. Override "remove-stale-when-updated" option regarding only the pull requests.
          remove-pr-stale-when-updated: ""
          # Run the processor in debug mode without actually performing any operations on live issues.
          debug-only: false # optional, default is false
          # The order to get issues or pull requests. Defaults to false, which is descending.
          ascending: false # optional, default is false
          # What to sort results by. Valid options are `created`, `updated`, and `comments`. Defaults to `created`.
          sort-by: created # optional, default is created
          # Delete the git branch after closing a stale pull request.
          delete-branch: false # optional, default is false
          # The date used to skip the stale action on issue/pull request created before it (ISO 8601 or RFC 2822).
          start-date: ""
          # The assignees which exempt an issue or a pull request from being marked as stale. Separate multiple assignees with commas (eg. "user1,user2").
          exempt-assignees: ""
          # The assignees which exempt an issue from being marked as stale. Separate multiple assignees with commas (eg. "user1,user2"). Override "exempt-assignees" option regarding only the issues.
          exempt-issue-assignees: ""
          # The assignees which exempt a pull request from being marked as stale. Separate multiple assignees with commas (eg. "user1,user2"). Override "exempt-assignees" option regarding only the pull requests.
          exempt-pr-assignees: ""
          # Exempt all issues and pull requests with assignees from being marked as stale. Default to false.
          exempt-all-assignees: false # optional, default is false
          # Exempt all issues with assignees from being marked as stale. Override "exempt-all-assignees" option regarding only the issues.
          exempt-all-issue-assignees: ""
          # Exempt all pull requests with assignees from being marked as stale. Override "exempt-all-assignees" option regarding only the pull requests.
          exempt-all-pr-assignees: ""
          # Exempt draft pull requests from being marked as stale. Default to false.
          exempt-draft-pr: false # optional, default is false
          # Display some statistics at the end regarding the stale workflow (only when the logs are enabled).
          enable-statistics: true # optional, default is true
          # A comma delimited list of labels to add when an issue or pull request becomes unstale.
          labels-to-add-when-unstale: ""
          # A comma delimited list of labels to remove when an issue or pull request becomes stale.
          labels-to-remove-when-stale: ""
          # A comma delimited list of labels to remove when an issue or pull request becomes unstale.
          labels-to-remove-when-unstale: ""
          # Any update (update/comment) can reset the stale idle time on the issues and pull requests.
          ignore-updates: false # optional, default is false
          # Any update (update/comment) can reset the stale idle time on the issues. Override "ignore-updates" option regarding only the issues.
          ignore-issue-updates: ""
          # Any update (update/comment) can reset the stale idle time on the pull requests. Override "ignore-updates" option regarding only the pull requests.
          ignore-pr-updates: ""
          # Only the issues or the pull requests with an assignee will be marked as stale automatically.
          include-only-assigned: false # optional, default is false
          # Only issues with a matching type are processed as stale/closed. Defaults to `[]` (disabled) and can be a comma-separated list of issue types.
          only-issue-types: ""
